# Generated by Django 4.2.7 on 2023-11-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biowebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recentactivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True)),
                ('date', models.DateField()),
                ('recent', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todate', models.DateField()),
                ('re_activity', models.CharField(max_length=100)),
                ('re_remarks', models.CharField(max_length=100)),
                ('re_status', models.CharField(max_length=100)),
            ],
        ),
    ]
