# Generated by Django 4.2.7 on 2023-11-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biowebsite', '0002_recentactivity_remark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='recentactivity',
        ),
    ]
