# Generated by Django 4.2.7 on 2023-11-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biowebsite', '0003_delete_recentactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ongoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True)),
                ('ongoing_activity', models.TextField()),
            ],
        ),
    ]
